/**
 * AUTO-GENERATED by scripts/sync-enabled-fabric-routes.mjs
 * Detected from src/app/fabrics/{slug}/page.tsx folders. Do not edit by hand.
 */
export const ENABLED_FABRIC_SLUGS = [
  "cotton",
  "silk",
  "linen",
  "blends",
  "viscose",
  "jute",
  "modal",
  "rayon",
  "tencil",
] as const;

export type EnabledFabricSlug = (typeof ENABLED_FABRIC_SLUGS)[number];

export function isEnabledFabricSlug(slug: string): boolean {
  return ENABLED_FABRIC_SLUGS.includes(slug.toLowerCase().trim() as EnabledFabricSlug);
}
