/**
 * AUTO-GENERATED by scripts/sync-enabled-fabric-routes.mjs
 * Detected from src/app/fabrics/{slug}/page.tsx folders. Do not edit by hand.
 */
export const ENABLED_FABRIC_SLUGS = [
  "wholesale-cotton-fabrics",
  "wholesale-silk-fabrics",
  "wholesale-linen-fabrics",
  "wholesale-blended-fabrics",
  "wholesale-jute-fabric",
  "wholesale-modal-fabric",
  "wholesale-rayon-fabric",
  "wholesale-viscose-fabric",
  "wholesale-tencel-fabric",
] as const;

export type EnabledFabricSlug = (typeof ENABLED_FABRIC_SLUGS)[number];

export function isEnabledFabricSlug(slug: string): boolean {
  return ENABLED_FABRIC_SLUGS.includes(slug.toLowerCase().trim() as EnabledFabricSlug);
}
